[pytest]
addopts = -vs --alluredir ./allure-results --clean-alluredir


markers =
    api: 標記所有 API 測試
    product_type: 標記商品類型模組
    check_reservation_availability: 標記檢查預約可用性的測試
    service_call: 標記服務呼叫模組測試
    tax_group: 標記稅務群組模組測試
    tax_type: 標記稅務類型模組測試